# Generated by Django 4.2.6 on 2023-10-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique FKs in cart'),
        ),
    ]
