# Generated by Django 4.2.6 on 2023-10-15 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0002_cart_unique_fks_in_cart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique FKs in cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_carts', to='products.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
