# Generated by Django 4.2.6 on 2023-10-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_unique_fks_in_cart_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=255)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
