# Generated by Django 4.2.6 on 2023-10-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_promocode_options_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='old_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
