# Generated by Django 4.2.6 on 2023-10-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_old_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='old_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
