# Generated by Django 4.2.6 on 2023-10-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cart_delivery_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
