# Generated by Django 4.2.6 on 2023-10-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_cart_is_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='all_user_carts_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
