# Generated by Django 4.2.6 on 2023-10-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cart_all_user_carts_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_discounted',
        ),
    ]
