# Generated by Django 4.2.6 on 2023-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('bid', models.IntegerField()),
                ('cbid', models.IntegerField()),
                ('size_grid_image', models.TextField(default=None, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('old_price', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('vendor_code', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'offers',
                'ordering': ('id',),
            },
        ),
    ]
