# Generated by Django 4.2.6 on 2023-10-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_categories'),
        ('offers', '0002_alter_offer_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
