# Generated by Django 4.2.6 on 2023-10-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='product_id',
            new_name='product',
        ),
    ]
