# Generated by Django 4.2.6 on 2023-10-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_rename_product_id_offer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='delivery_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='purchasable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='use_bonuses',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
