# Generated by Django 4.2.6 on 2023-10-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offer_delivery_offer_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
