# Generated by Django 4.2.6 on 2023-10-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_color',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_color',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
