# Generated by Django 4.2.6 on 2023-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='Воронеж', null=True)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(default='В обработке', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'orders',
                'ordering': ('-created',),
            },
        ),
    ]
