# Generated by Django 4.2.6 on 2023-10-16 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='Воронеж', null=True)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(default='В обработке', max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'orders',
                'ordering': ('-created',),
            },
        ),
    ]
