# Generated by Django 4.2.6 on 2023-10-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_discount'),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='offers',
            field=models.ManyToManyField(blank=True, to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
