# Generated by Django 4.2.6 on 2023-10-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_old_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('barcode', models.CharField(default=None, max_length=255, null=True)),
                ('discount', models.IntegerField(blank=True, default=None, null=True)),
                ('default_available', models.BooleanField(default=False)),
                ('description', models.TextField(default=None, null=True)),
                ('purchasable', models.BooleanField(default=True)),
                ('preorder', models.BooleanField(default=False)),
                ('url', models.TextField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ('-viewed_at',),
            },
        ),
    ]
