# Generated by Django 4.2.6 on 2023-10-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_parameter_remove_productparameter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparameter',
            name='parameter',
        ),
        migrations.AddField(
            model_name='productparameter',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
